package net.ddns.encante.telegram.hr.hue.api;

import com.google.gson.annotations.SerializedName;

public enum HueType {
    @SerializedName("device")
    DEVICE,
    @SerializedName("bridge_home")
    BRIDGE_HOME,
    @SerializedName("room")
    ROOM,
    @SerializedName("zone")
    ZONE,
    @SerializedName("light")
    LIGHT,
    @SerializedName("button")
    BUTTON,
    @SerializedName("relative_rotary")
    RELATIVE_ROTARY,
    @SerializedName("temperature")
    TEMPERATURE,
    @SerializedName("light_level")
    LIGHT_LEVEL,
    @SerializedName("motion")
    MOTION,
    @SerializedName("entertainment")
    ENTERTAINMENT,
    @SerializedName("grouped_light")
    GROUPED_LIGHT,
    @SerializedName("device_power")
    DEVICE_POWER,
    @SerializedName("zigbee_bridge_connectivity")
    ZIGBEE_BRIDGE_CONNECTIVITY,
    @SerializedName("zigbee_connectivity")
    ZIGBEE_CONNECTIVITY,
    @SerializedName("zgp_connectivity")
    ZGP_CONNECTIVITY,
    @SerializedName("bridge")
    BRIDGE,
    @SerializedName("zigbee_device_discovery")
    ZIGBEE_DEVICE_DISCOVERY,
    @SerializedName("homekit")
    HOMEKIT,
    @SerializedName("matter")
    MATTER,
    @SerializedName("matter_fabric")
    MATTER_FABRIC,
    @SerializedName("scene")
    SCENE,
    @SerializedName("entertainment_configuration")
    ENTERTAINMENT_CONFIGURATION,
    @SerializedName("public_image")
    PUBLIC_IMAGE,
    @SerializedName("auth_v1")
    AUTH_V1,
    @SerializedName("behavior_script")
    BEHAVIOR_SCRIPT,
    @SerializedName("behavior_instance")
    BEHAVIOR_INSTANCE,
    @SerializedName("geofence")
    GEOFENCE,
    @SerializedName("geofence_client")
    GEOFENCE_CLIENT,
    @SerializedName("geolocation")
    GEOLOCATION,
    @SerializedName("smart_scene")
    SMART_SCENE
}
